In [ ]:
import pandas as pd

In [ ]:
path="/content/drive/MyDrive/Colab Notebooks/smsdatanewdataset.csv"

In [ ]:
df=pd.read_csv(path)

In [ ]:
df

     Unnamed: 0  ... BankTrancation
0             1  ...            Yes
1             2  ...            Yes
2             3  ...             no
3             4  ...             no
4             5  ...             no
..          ...  ...            ...
488         489  ...             No
489         490  ...             No
490         491  ...             No
491         492  ...             No
492         493  ...             No

[493 rows x 4 columns]

In [ ]:
df=df[['address','body','BankTrancation']]

In [ ]:
df

       address  ... BankTrancation
0    BW-SBGPPC  ...            Yes
1    BW-SBGPPC  ...            Yes
2    HP-TATAMF  ...             no
3    BH-NSESMS  ...             no
4    BH-NSESMS  ...             no
..         ...  ...            ...
488  BH-MBBSHN  ...             No
489  BW-mbbsss  ...             No
490   9.19E+11  ...             No
491  BW-GMSHOP  ...             No
492   9.20E+11  ...             No

[493 rows x 3 columns]

In [ ]:
low_body=[]

for data in df['body']:
  data=data.lower()
  low_body.append(data)

In [ ]:
df['body']=low_body

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df.head()

     address                                               body BankTrancation
0  BW-SBGPPC  transaction of  inr 2000.00  made on prepaid c...            Yes
1  BW-SBGPPC  transaction of  inr 3000.00  made on prepaid c...            Yes
2  HP-TATAMF  your account statement for recent transaction ...             no
3  BH-NSESMS  dear aodxxxxx8r,your traded value for 12-jan-1...             no
4  BH-NSESMS  dear aamxxxxx1q,your traded value for 17-jan-1...             no

In [ ]:
low_banktr=[]
for tr in df['BankTrancation']:
  tr=tr.lower()
  low_banktr.append(tr)

In [ ]:
df['BankTrancation']=low_banktr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df.head()
df.describe()

         address                  body BankTrancation
count        493                   493            493
unique       131                   439              2
top     9.20E+11  i'll call you later.             no
freq          73                     7            420

In [ ]:
df['BankTrancation'].value_counts()

no     420
yes     73
Name: BankTrancation, dtype: int64

In [ ]:
import string

def remove_punctuation(text):
  for punctuation in string.punctuation:
    text=text.replace(punctuation,'')
  return text

In [ ]:
df['body']=df['body'].apply(remove_punctuation)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df.head()

     address                                               body BankTrancation
0  BW-SBGPPC  transaction of  inr 200000  made on prepaid ca...            yes
1  BW-SBGPPC  transaction of  inr 300000  made on prepaid ca...            yes
2  HP-TATAMF  your account statement for recent transaction ...             no
3  BH-NSESMS  dear aodxxxxx8ryour traded value for 12jan18 c...             no
4  BH-NSESMS  dear aamxxxxx1qyour traded value for 17jan18 c...             no

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector=CountVectorizer()

In [ ]:
smsbody=list(df['body'])
type(smsbody)
print(smsbody)

['transaction of  inr 200000  made on prepaid card xxxx1407   on mon jan 01 113647 ist 2018  at cashatm1st ashram rd branch ahmadabad cit1224  current balance is inr 141000', 'transaction of  inr 300000  made on prepaid card xxxx1407   on mon jan 08 162312 ist 2018  at cashatm2nd atm ashram road   ahmedabad    4063  current balance is inr 325600', 'your account statement for recent transaction in folio no3791641 with tata mutual fund is available in the below link please click the below link valid for 5 days and enter your pan in capitals in case pan is not registered in the folio enter your folio no to download the statement of account wwwcamsonlinecomdnldresultaspfnamettotmcg3onrj845pdf  tatamf', 'dear aodxxxxx8ryour traded value for 12jan18 cm rs 26445 check your registered email for details contact broker', 'dear aamxxxxx1qyour traded value for 17jan18 cm rs 312401 check your registered email for details contact broker', 'sihl amt of rs 3096000 credited in your bank through ecs on 19012018 for sihl trading code itaj003  please check your bank account in 2 days to confirm credit', 'dear aodxxxxx8ryour traded value for 29jan18 cm rs 22250 check your registered email for details contact broker', 'sip installment of rs5000 in tata equity pe fund reg pl growth in folio no3791641 is due on 05feb18 please maintain sufficient balance in your state bank of india account  tata mf', 'total tds by employer of pan aamxxxxx1q for qtr ending dec 31 is rs 99190 and cumulative tds for fy 1718 is rs 732676 view 26as for details', 'sihl code itaj003 nseeq 2018025 gspl bq 100 ba 18800 sonasteer bq 75 ba 9830 todays bill amount 2629500 dr ledger bal 2629500 dr branch contact num 41072222', 'purchase sip in folio 379164173 in tata equity pe fund reg pl growth for rs500000 for 36239 units at nav of rs1379747 dated 05feb2018 is successful with applicable load if any  tata mf', 'sihl amt of rs 2629500 credited to sihl trading code itaj003 vide chq no 50557 drawn from state bank of india on date 06022018 ', 'your account statement for recent transaction in folio no3791641 with tata mutual fund is available in the below link please click the below link valid for 5 days and enter your pan in capitals in case pan is not registered in the folio enter your folio no to download the statement of account wwwcamsonlinecomdnldresultaspfnamet4c1vk3wogrf238pdf  tatamf', 'dear sir namaskar isir i would like to know have you got phd thesis of mine student er sukhwinder singh punjabi university with regards dr lakhwinder kaur prof ce pup', 'transaction of  inr 150000  made on prepaid card xxxx1407   on mon feb 19 150117 ist 2018  at cashatm2nd atm ashram road   ahmedabad    1508  current balance is inr 191100', 'hcg2468', 'please notify any unauthorized electronic transaction on dedicated toll free nos 1800112211  18004253800 immediately longer the time taken to notify higher would be risk of loss to you sbi prepaid team', 'sip installment of rs5000 in tata equity pe fund reg pl growth in folio no3791641 is due on 05mar18 please maintain sufficient balance in your state bank of india account  tata mf', 'respected sir\r\nsorry for the inconvenience occurred during the call\r\nsir our managers no 8138881000\r\nour managers name  mrjoby thomas', 'your lpg connection is deactivate because of 1 year inactivity in your lpg accountfor reactivation contact distributor with kyc and unified form', 'you have successfully initiated the individual pension account opening process through enps your acknowledgement no is 11479910 and the acknowledgement date is 01mar2018', 'your individual pension account under enps has been opened your permanent retirement account number pran is 110162241951 you are requested to submit the printed form at the earliest', 'ma amitbhai congratulation for tripura and entire north east presence ajay', 'आपके द्वारा प्रेषित शुभकामनाओं के लिए हृदय से अभिनंदन।\r\n\r\nअमित शाह', 'manage  contribute in your nps account on the go download nsdl nps mobile app android user click httpbitly2jwwaxf ios user click httpbitly2mzyu07', 'purchase sip in folio 379164173 in tata equity pe fund reg pl growth for rs500000 for 36607 units at nav of rs1365859 dated 05mar2018 is successful with applicable load if any  tata mf', 'units against nps contribution voluntary of rs 4980000 credited to your pran xx1951 with nav as of 050318 visit wwwcransdlcom for details', 'your account statement for recent transaction in folio no3791641 with tata mutual fund is available in the below link please click the below link valid for 5 days and enter your pan in capitals in case pan is not registered in the folio enter your folio no to download the statement of account wwwcamsonlinecomdnldresultaspfnamet3ofwlwwe4wk765pdf  tatamf', 'transaction of  inr 120000  made on prepaid card xxxx1407   on wed mar 14 150218 ist 2018  at cashatmsbi ashirwad complex  ahmedabad    9291  current balance is inr 309800', 'good afternoon sir\r\n\r\nrimica from kk sales abad\r\nplease send your email id so that i can send you brochure and details', 'ajayparikhgvpgmailcom', 'transaction of  inr 100000  made on prepaid card xxxx1407   on sat mar 24 100848 ist 2018  at cashatm1st ashram rd branch ahmadabad cit8192  current balance is inr 209800', 'a802 satymev vista gandhinagar sharkhej highway gota bridge gota', 'sip installment of rs5000 in tata equity pe fund reg pl growth in folio no3791641 is due on 05apr18 please maintain sufficient balance in your state bank of india account  tata mf', '09924486804\r\nkamal chimney fittings', 'your ac xxx5662 is credited with inr 12466 on 01apr2018 045722 pm by interest  avlbal inr 1456782', 'europa 9227405866', 'thx arcindbhai', 'dear customer your purchase request for euroclean is processed by our sales representative jeevaram ghanchi9998114740 for tcs click httpbitly2gre8g5', 'dear friend for life you will be happy to know that your request for euroclean has been processed your customer id is 6000885383  have a healthy day', 'प्रिय ग्राहक आपके युरेका फोर्ब्स खरेदी अनुभव के बारे में हमें  बतायें और बेहतर सेवा देने में मदद किजीये । क्लिक करें httpltmsinrj8fjwifn', 'dear ajay parikh help us serve you better by giving feedback on your purchase experience itll take only seconds click httpltmsinrk3kbzdmjzn', 'rs4000000 debited to sbxxx1796 acbal17769937 clrbal 17769937 self  bodakdev on 05042018 124039iob', 'value of investment in respect of your nps tier i account xx1951 as of 31032018 is rs 5087861 view transaction statement at wwwcransdlcom', 'purchase sip in folio 379164173 in tata equity pe fund reg pl growth for rs500000 for 36358 units at nav of rs1375198 dated 05apr2018 is successful with applicable load if any  tata mf', 'please note that the base ter for tata equity pe fund regular plan  growth is changed to 185  wef 05042018', 'sorry for delay in sending report of kanubhai please give me one week by next monday  i will post it', 'ok', 'ajay parikh b8 balaji park nr lad society sandesh press road nr page one hotel  vastrapur ', 'thanks for choosing jaquaryour registered tel no with customer care is 9426587062 which be quoted for service assistance customer care toll free 18001216808', 'thanks for choosing jaquar a complete bathing solution company the registered service call reference no is 00311246 customer care toll free 18001216808', ' ', 'ajay parikh a 802 satymev vista sharkhej gandhinagar highway gota fly over bridge nr water tank gota', 'dear customer break up of consolidated charges for mar2018 for ac no xxxx9259 \r\nvalue added sms alert fee rs 15 \r\ntotal rs 15 excluding gst ', 'dear customer your ticket no is 2000884677 ifb representative will visit shortly for assistance please call 180030005678 18604255678', 'aampp7411q', 'please note that the base ter for tata equity pe fund regular plan  growth is changed to 186  wef 13042018', 'dear customer your ticket 2000884677 has been assigned to ifb service technician who will contact you shortly', 'ifb 9033011632 aditya enterprises', 'ajay parikh b 8 balaji park sandesh press road nr page one hotel vastrapur  to gota a802 satymev visit nr gota fly over ', 'dear customer ifb ticket no 2000884677 has been closed if resolved  sms  yesif not  sms no to 9231004321 from reg no 9426587062', 'your samsung product request number is 4258744008 use this for any future reference at 180040samsung7267864 or track online at httpbitly1tzjxtz', 'dear customer service engineer vijay mobile number  9099097560 has been assigned against registered service order 4258854915', 'dear customer service engineer vijay contact 9099097560 has been assigned against your service request 4258854915 for support please call 180040samsung7267864', '      ', 'dear customer service order 4258854915 has been cancelledproduct replaced by dealerplease contact us on 180040samsung7267864 for any assistance', 'ajay parikh a 802 satymev vista sharkhej gandhinagar highway gota fly over bridge nr water tank gota', 'your samsung product request number is 4258878075 use this for any future reference at 180040samsung7267864 or track online at httpbitly1tzjxtz', 'dear siri have discussed your case with respective team and will be resolved by eod regards', 'same as yesterday ', 'dr ajay parikh department of computer sc gujarat vidyapith nr sbi ashram road incomtax ahmedabad', 'congratulations on your samsung product purchase you are now eligible for samsung smart club membership benefits to enroll your membership 943477608883 visit wwwsamsungsmartclubin within 90 days from date of purchase tc apply', 'pnr8426936101trn12297doj0805183aadipunedp2230\r\nhitarth parilkh1rac 57rac 58\r\nfare3100this rail travel is insured\r\n', 'pnr8558482155trn12297doj0805183aadipunedp2230\r\najay parikh1wl 1wl 2\r\nfare3100sc00pg chgs\r\n', 'dear iob customeryour 15g form for the financial year 201819 has been registered on 23apr18use iob mpassbook app for instant access to account details', 'pnr8104811701trn12298doj1205183apuneadidp2135\r\najay parikh3b1 11b1 13b1 14b1 16\r\nfare6200this rail travel is insured\r\n', 'please note that the base ter for tata equity pe fund regular plan  growth is changed from 186 to 185 wef 23042018   tata mf', 'dear iob customeryour rdp dep ac 000001286 maturing on 28apr18 will be auto renewedfor any change in amountperiod contact branch before 28apr18', 'dear iob customeryour rdp dep ac 000001285 maturing on 28apr18 will be auto renewedfor any change in amountperiod contact branch before 28apr18', 'pl check the email sent detailing necessary prerequisite for claiming exemtion us1011 and to be taken while filing itr7 same in efiling portal', 'sip installment of rs5000 in tata equity pe fund reg pl growth in folio no3791641 is due on 05may18 please maintain sufficient balance in your state bank of india account  tata mf', 'hello your cheque no 404530 for rs 3600 which was issued from ac no xxxx9259 has been received in clearing on 02052018', 'transaction of  inr 200000  made on prepaid card xxxx1407   on wed may 02 140001 ist 2018  at cashatmsbi  ashram road bran ahmedabad    8865  current balance is inr 17700', 'hello your form 15 g has been updated against your customer id xx4401 this is valid for the current financial year have a nice day', 'i will b in ahmedabad today', 'r u there', 'just now boarded from delhi', 'yes', 'welcome', 'balance in savings ac 019259 as of 03may2018 eod is inr 14731094 credits in ac are subject to clearing', 'what about lunch ', 'we will take from here\r\nafternoon u can join with us to c venue at gujrat univ convention centre', 'is it possible for u', 'yes', 'what time at guj uni convention center', 'hello ajaybhai\r\nthe car owner will let me know within an hour he is one of my friends friend\r\n', 'a 802 satymev vista nr gota flyover s g highway gota', 'at home', 'waiting for you are you coming ', 'dear customer please ignore the earlier sms communication sent on 04apr2018 on the revised locker rent the fy 201819 rental for your locker no 359 held with vastrapur branch is rs 1700  gst', 'pnr8426936101\r\ntrn12297\r\ndt08052018\r\nfrm adi to pune\r\ncls3a\r\np1cnf\r\np2cnf\r\nfinal status may change after charting \r\n helpline no \r\n customer care 138  security 182', 'make all necessary  arrangment regarding admission process i will be back on 13th', 'pnr8426936101\r\ntrn12297\r\ndt08052018\r\nfrm adi to pune\r\ncls3a\r\np1b726\r\np2b727\r\nchart prepared \r\n helpline no \r\n customer care 138  security 182', 'pnr8558482155\r\ntrn12297\r\ndt08052018\r\nfrm adi to pune\r\ncls3a\r\np1b225\r\np2b226\r\nchart prepared \r\n helpline no \r\n customer care 138  security 182', 'dear customer payment of rs 68600  for customer id 1000217118 was received by ebpp on date 08may18  adani gas', 'greetings from mit institute of design kindly report to the institute for studio test and personal interview on 1152018 900am for queries9209800600', 'hello your ac no 019259 has been debited by rs 2006 on 09may18 the ac balance is rs 14530494 info rent for 201819 locker no 359', 'please note that the base ter for tata equity pe fund regular plan  growth is changed from 185 to 184 wef 09052018   tata mf', 'dear customer bill for airtel fixedlinebroadband no 7029602320 dated 27apr18 of rs 3304 is due on 16may18 you can now make your bill payment with my airtel app click wwwairtelin5dsl  ignore this sms if you have paid ', 'pnr 8104811701 train 12298 is expected to arrive at ahmedabad jn at 0620 hrs on 13may2018', 'dear applicant your sbi card application 2111006021638 is under processing and we will update you the status within 5 working days you can also check application status at wwwsbicardcom ', 'dear customer bill for airtel fixedlinebroadband no 7029602320 dated 27apr18 of rs 3304 is due on 16may18 you can now make your bill payment with my airtel app click wwwairtelin5dsl  ignore this sms if you have paid ', 'greetings from iob\r\n\r\nour branches are conducting customer service meetgrievance redressal day on 15052018\r\n\r\nplease participate  give suggestions', 'nikunj vakani 8866761970\r\ngls product design student\r\nfor hitarth \r\n\r\nfrom rutvij dasadia balaji park', 'thx', 'i am in program i will call you ', 'ajayparikhgvpgmailcom', 'congratulation to ma amitbhai and best wishes to form a govt in ktaka\r\najay parikh ', 'congratulation to ma amitbhai and best wishes to form a govt in ktaka\r\najay parikh ', 'air india flight ai030 amdbom on 20may2018 shall depart at 0330 hours ai tollfree 18001801407', 'congratulations your sbi card app no2111006021638 has been approved card will reach you  in 7 working days you can now manage your account online at wwwsbicardcom ', 'dear customer with your samsung purchase you are now eligible for smart club membership enroll with your membership no 943477608883 at wwwsamsungsmartclubin  enjoy great benefits enroll within 90 days from date of product purchased to avoid membership lapse tc apply', 'dear hitarth congratulationskindly pay your fees using below link and  roll nodatah0036€ httpsgooglrka6in ignore in case you have already paid', 'dear customer bill of rs 3304 for airtel fixedlinebroadband account no 7029602320 dated 27apr18 is due today to pay through my airtel app click wwwairtelin5dsl  ignore this sms if you have paid  ', 'your sbi card has been sent on 15may18 through aramex ref no ev18135063934same will reach within 4 working daysstatus can be tracked thru wwwaramexcom', 'you may invite vijay chothaiwala and unna t at gujarat vidyapith for evening tea or dinner', 'if possible', 'i already sent message to unnat', 'sure sir', 'renewal premium rs 12 of pmsby is due on 31052018 please contact your banks branch to renew the policy with national insurance', 'dear hitarth ajay parikhgentle reminderkindly pay the fees using below link and roll no datah0036  to confirm your admission by 5pm today httpsgooglrka6in kindly ignore if already paid', 'dear hitarth ajay parikhgentle reminderkindly pay the fees using below link and roll no datah0036 to confirm your admission by 5pm today httpsgooglrka6in kindly ignore if already paid', 'balance in savings ac 019259 as of 17may2018 eod is inr 14530494 credits in ac are subject to clearing', 'paper is ready pl sms me email id so that i can send you paper', 'sent', 'nameh parikh\r\nphone076981 63466\r\nphone7698163466\r\n', 'pnr8705734678trn12934doj020618ccadistdp0455\r\najay parilhc2 51\r\nfare415this rail travel is insured\r\n', 'pnr8105744415trn12933doj020618ccstadidp1740\r\najay parikhc2 23\r\nfare415this rail travel is insured\r\n', 'reminder bill payment of rs 3304 for airtel fixedlinebroadband account no 7029602320 is overdue since 16may18 period 26mar18 to 25apr18 pay now with my airtel app wwwairtelin5dsl  please ignore if paid  ', 'iimb hostel block nr amul parl', 'ok', 'silver indica  7003', 'ok', 'sms me', 'sir i am nirav from iite gandhinagar our vc sir will mail u for some work kindly do the needful ', 'ok', 'thanks sir', 'reminder bill payment of rs 3304 for airtel fixedlinebroadband account no 7029602320 is overdue since 16may18 period 26mar18 to 25apr18 pay now with my airtel app wwwairtelin5dsl  please ignore if paid  ', 'dear customer pradhan mantri suraksha bima policy expires on 31052018 pl contact your bank for auto debiting rs 12 as premium from your saving bank ac regards nicl', 'rs15000 was spent on your sbi card ending 6495 at asia 7 on 260518 available credit limit rs10596700 download app at httpsgooglb7qdqu', 'your ac xxx5662 is debited with inr 1500 on 26may2018 062527 pm by trfr avl bal inr 1455282', 'yet i havent received any mail from vc sir', '9428919057', '1272124460', 'let me know status', 'nameajay parikh guj vidyapith\r\nphone9426587062\r\nphone919426587062\r\n', 'sip installment of rs5000 in tata equity pe fund reg pl growth in folio no3791641 is due on 05jun18 please maintain sufficient balance in your state bank of india account  tata mf', 'dear customer your invoice no r201810226515 of rs 23000  for customer id 1000217118 is generated on date 31may18 payment due on 15jun18  adani gas', 'bill payment of rs 3304 for your airtel fixedlinebroadband account no 7029602320 26mar18 to 25apr18is 15 days overdue  new bill of rs 118 is ready pay rs 3422 today with my airtel app wwwairtelin5dsl please ignore if paid', 'transaction of  inr 200000  made on prepaid card xxxx1407   on fri jun 01 143818 ist 2018  at cashatm2nd atm ashram road   ahmedabad    6537  current balance is inr 182000', 'namskar  sir \r\najay bhai patil 918460860106\r\nkarnavati par leva aavshe \r\ndr bhavesh i raval', 'thx', 'sorry is it possible on monday', 'dear customer payment of rs 23000  for customer id 1000217118 was received by debitcardpt on date 03jun18  adani gas', '28 shares of tcs credited in your demat ac xxxx4499 on 040618 in respect of bonus listingtrading  approval awaited nsdl', '166 shares of tcs credited in your demat ac xxxx9637 on 040618 in respect of bonus listingtrading  approval awaited nsdl', 'admission guidance\r\nmbbs in india\r\n\r\narmenia\r\ngeorgia\r\nukrain\r\nchina\r\n\r\nbamsbhmsbdsdental\r\n\r\npatel education anand\r\n\r\nyatin patel\r\n9662038262\r\n\r\nvishal patel\r\n9687088813', 'dear sbi cardholder now enjoy easy access to exclusive services and account information with just a click visit our website wwwsbicardcom or download the sbi card mobile app from httpbitlysbicardapp to access selfservicing options on the go', 'congratsyou r selected for aircraft maintenance engineering in wiiaahmedabadapproved by dgcagovtof indialast date for registration 9618call7227037783', 'on your request mobile no xxxxxx7062 has been updated in account no xxxxx591614 if not requested please contact your branch', 'on your request cheque book has been issued in account no xxxxx591614 if not requested please contact your branch', 'ajayparikhgvpgmailcon', 'ajayparikhgvpgmailcom', 'on your request address has been changed in account no xxxxx591614 if not requested please contact your branch', 'your ac xxxxx591614

In [ ]:
count_vector.fit(smsbody)

CountVectorizer()

In [ ]:
word_list = count_vector.get_feature_names()
len(word_list)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

2013

In [ ]:
doc_array = count_vector.transform(smsbody).toarray()
doc_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
frequency_matrix = pd.DataFrame(doc_array,
                                columns = word_list)
frequency_matrix

     000001285  000001286  00019259  001230892648if  ...  मन  हक  हतर  हम
0            0          0         0               0  ...   0   0    0   0
1            0          0         0               0  ...   0   0    0   0
2            0          0         0               0  ...   0   0    0   0
3            0          0         0               0  ...   0   0    0   0
4            0          0         0               0  ...   0   0    0   0
..         ...        ...       ...             ...  ...  ..  ..  ...  ..
488          0          0         0               0  ...   0   0    0   0
489          0          0         0               0  ...   0   0    0   0
490          0          0         0               0  ...   0   0    0   0
491          0          0         0               0  ...   0   0    0   0
492          0          0         0               0  ...   0   0    0   0

[493 rows x 2013 columns]

In [ ]:
text_counts=count_vector.fit_transform(df['body'])

In [ ]:
text_counts

<493x2013 sparse matrix of type '<class 'numpy.int64'>'
	with 7811 stored elements in Compressed Sparse Row format>

In [ ]:
x=df['body']
y=df['BankTrancation']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=5,test_size=0.20)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn import naive_bayes, metrics

In [ ]:
mnb=MultinomialNB()

In [ ]:
# mnb.fit(x_train,y_train)
x_train_count=count_vector.transform(x_train)
x_test_count=count_vector.transform(x_test)

In [ ]:
classifier =naive_bayes.MultinomialNB()
classifier.fit(x_train_count, y_train)

predictions = classifier.predict(x_test_count)

In [ ]:
#create dataframe for y-test and y-pred result show

In [ ]:
predictions

array(['no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'yes', 'no',
       'no', 'no', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'no', 'yes',
       'no', 'no', 'yes', 'no', 'yes', 'no', 'yes', 'no', 'no', 'no',
       'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no',
       'no', 'no', 'no', 'yes', 'yes', 'no', 'no', 'no', 'yes', 'no',
       'no', 'yes', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'yes', 'no', 'no', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no',
       'yes', 'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no',
       'yes', 'no', 'no', 'no', 'no', 'yes'], dtype='<U3')

In [ ]:
print(metrics.accuracy_score(predictions, y_test))

0.8686868686868687

In [ ]:
https://towardsdatascience.com/building-a-naive-bayes-machine-learning-model-to-classify-text-71431ce20844